---
vars:
  timezone: "America/Argentina/Buenos_Aires"

handlers:
  - name: update tzdata
    command: dpkg-reconfigure --frontend noninteractive tzdata

tasks:
  - name: set /etc/localtime to {{ timezone }}
    copy: src=/usr/share/zoneinfo/{{ timezone }}
          dest=/etc/localtime
          owner=root
          group=root
          mode=0644
          backup=yes

  - name: set /etc/timezone to {{ timezone }}
    copy: dest=/etc/timezone content="{{ timezone }}"
    notify: update tzdata
