- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ user_home }}/.oh-my-zsh"

- name: create new zshrc file
  copy:
    src: "{{ user_home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ user_home }}/.zshrc"
