- name: install wicd
  apt: name={{ item }} state=present
  with_items:
    - wicd
    - wicd-curses

- name: install wifi scanning tools
  apt: name={{ item }} state=present
  with_items:
    - aircrack-ng
    - kismet
    - kismet-plugins
